version: 0.2

phases:
  install:
    commands:
      - echo Installing Serverless...
      - npm install -g serverless
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - echo Creating new aws named-profiles for both dev and prod usage...
      - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_DEV --secret $AWS_SECRET_DEV --profile devServerless
      - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_PROD --secret $AWS_SECRET_PROD --profile prodServerless
  build:
    commands:
      - echo Deployment started on `date`
      - echo Deploying with Serverless Framework...
      - serverless deploy --stage $NODE_ENV --verbose
  post_build:
    commands:
      - echo Deployment completed on `date`
